spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/sed_market?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 1000
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0

mybatis:
  type-aliases-package: com.iverson.sed_erp.pojo
  configuration:
    map-underscore-to-camel-case: true
server:
  servlet:
    context-path: /erp
